import { Router } from 'express';
import { readState, replaceState, withTransaction } from '../../db/database.js';
import { INITIAL_STATE } from '../../db/initial-state.js';
import { requireRole } from '../../middleware/auth.js';
import { userPermissions } from '../../security/permissions.js';
export const stateRouter=Router();
stateRouter.get('/',async(req,res,next)=>{try{res.json(await readState(undefined,req.user,req.companyId));}catch(e){next(e);}});
stateRouter.put('/',async(req,res,next)=>{try{const operations=String(req.get('X-WMS-Operation')||'').split(',').map(x=>x.trim()).filter(Boolean),siteId=String(req.get('X-WMS-Site')||'').trim(),permissions=userPermissions(req.user,req.companyId,siteId),required={codesAssociate:'codesAssociate',productsEdit:'productsEdit',inventoryAdjust:'inventoryAdjust',palletsOperate:'palletsOperate',palletsRegister:'palletsRegister'};for(const operation of operations){const permission=required[operation];if(permission&&!permissions[permission])return res.status(403).json({error:'Tu permiso personalizado no autoriza esta operación.'});}const expected=req.body?.meta?.revision,compact=req.get('X-WMS-Compact')==='1';const nextState=await withTransaction(c=>replaceState(c,req.body,expected,req.user,compact,req.companyId));res.json(nextState);}catch(e){next(e);}});
stateRouter.post('/reset',requireRole('ADMIN_GLOBAL','ADMINISTRADOR'),async(req,res,next)=>{try{if(req.companyId!=='SERCO_RIEGO')return res.status(400).json({error:'El restablecimiento de demostración solo está disponible para la empresa inicial.'});const current=await readState(undefined,req.user,req.companyId),{companies:_companies,users:_users,...initialTenant}=INITIAL_STATE;const fresh={...initialTenant,shipments:[],tasks:[],session:{userId:req.user.id},meta:{...INITIAL_STATE.meta,revision:current.meta.revision}};res.json(await withTransaction(c=>replaceState(c,fresh,current.meta.revision,req.user,false,req.companyId)));}catch(e){next(e);}});
