import { Router } from 'express';
import { pool, ENTITY_TABLES } from '../../db/database.js';
import { tenantItem } from '../../security/tenant.js';

const allowed=new Set(ENTITY_TABLES);
function tableFor(req){const t=req.params.entity;if(!allowed.has(t))throw Object.assign(new Error('Módulo no válido.'),{status:404});return t;}
function selectSql(t){return t==='products'?'SELECT data FROM products WHERE company_id=$1 ORDER BY code':t==='inventory'?'SELECT data FROM inventory WHERE company_id=$1 ORDER BY id':`SELECT data FROM ${t} WHERE company_id=$1 ORDER BY id`;}
async function upsert(t,item,companyId){
 if(!item?.id)throw Object.assign(new Error('El campo id es obligatorio.'),{status:400});
 const scoped=tenantItem(item,companyId);
 if(t==='companies')throw Object.assign(new Error('Las empresas se administran desde el estado global.'),{status:400});
 if(t==='products')return pool.query('INSERT INTO products(id,code,data,company_id) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(company_id,id) DO UPDATE SET code=EXCLUDED.code,data=EXCLUDED.data RETURNING data',[scoped.id,scoped.code,JSON.stringify(scoped),companyId]);
 if(t==='inventory')return pool.query('INSERT INTO inventory(id,product_code,location_id,qty,pallet_id,data,company_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) ON CONFLICT(company_id,id) DO UPDATE SET product_code=EXCLUDED.product_code,location_id=EXCLUDED.location_id,qty=EXCLUDED.qty,pallet_id=EXCLUDED.pallet_id,data=EXCLUDED.data RETURNING data',[scoped.id,scoped.productCode,scoped.locationId,Number(scoped.qty||0),scoped.palletId||null,JSON.stringify(scoped),companyId]);
 return pool.query(`INSERT INTO ${t}(id,data,company_id) VALUES($1,$2::jsonb,$3) ON CONFLICT(company_id,id) DO UPDATE SET data=EXCLUDED.data RETURNING data`,[scoped.id,JSON.stringify(scoped),companyId]);
}
export const entityRouter=Router();
entityRouter.post('/orders/:id/emit',async(req,res,next)=>{const client=await pool.connect();try{const companyId=req.companyId,{order,inventory=[],deleteInventoryIds=[],transfer=null,shipment=null}=req.body||{},safeOrder=tenantItem(order,companyId);if(!safeOrder?.id||safeOrder.id!==req.params.id)return res.status(400).json({error:'La orden emitida no es válida.'});if(safeOrder.status!=='EMITIDA')return res.status(400).json({error:'La orden debe quedar en estado EMITIDA.'});await client.query('BEGIN');const current=(await client.query('SELECT data FROM orders WHERE company_id=$1 AND id=$2 FOR UPDATE',[companyId,safeOrder.id])).rows[0]?.data;if(!current){await client.query('ROLLBACK');return res.status(404).json({error:'La orden ya no existe en esta empresa.'});}if(!['PENDIENTE_EMISION','PREPARADA'].includes(current.status)){await client.query('ROLLBACK');return res.status(409).json({error:`La orden está en estado ${current.status} y no puede emitirse nuevamente.`});}for(const raw of inventory){const row=tenantItem(raw,companyId);await client.query('INSERT INTO inventory(id,product_code,location_id,qty,pallet_id,data,company_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) ON CONFLICT(company_id,id) DO UPDATE SET product_code=EXCLUDED.product_code,location_id=EXCLUDED.location_id,qty=EXCLUDED.qty,pallet_id=EXCLUDED.pallet_id,data=EXCLUDED.data',[row.id,row.productCode,row.locationId,Number(row.qty||0),row.palletId||null,JSON.stringify(row),companyId]);}for(const id of deleteInventoryIds)await client.query('DELETE FROM inventory WHERE company_id=$1 AND id=$2',[companyId,id]);for(const [table,raw] of [['transfers',transfer],['shipments',shipment]])if(raw?.id){const row=tenantItem(raw,companyId);await client.query(`INSERT INTO ${table}(id,data,company_id) VALUES($1,$2::jsonb,$3) ON CONFLICT(company_id,id) DO UPDATE SET data=EXCLUDED.data`,[row.id,JSON.stringify(row),companyId]);}await client.query('UPDATE orders SET data=$3::jsonb WHERE company_id=$1 AND id=$2',[companyId,safeOrder.id,JSON.stringify(safeOrder)]);await client.query('UPDATE wms_company_meta SET revision=revision+1,updated_at=now() WHERE company_id=$1',[companyId]);await client.query('COMMIT');res.json({order:safeOrder,inventory,deleteInventoryIds,transfer,shipment});}catch(e){await client.query('ROLLBACK').catch(()=>{});next(e);}finally{client.release();}});
entityRouter.get('/:entity',async(req,res,next)=>{try{const t=tableFor(req);if(t==='companies')return res.status(400).json({error:'Usa el estado autorizado para consultar empresas.'});res.json((await pool.query(selectSql(t),[req.companyId])).rows.map(r=>r.data));}catch(e){next(e);}});
entityRouter.get('/:entity/:id',async(req,res,next)=>{try{const t=tableFor(req);if(t==='companies')return res.status(400).json({error:'Usa el estado autorizado para consultar empresas.'});const r=(await pool.query(`SELECT data FROM ${t} WHERE company_id=$1 AND id=$2`,[req.companyId,req.params.id])).rows[0];if(!r)return res.status(404).json({error:'Registro no encontrado en esta empresa.'});res.json(r.data);}catch(e){next(e);}});
entityRouter.post('/:entity',async(req,res,next)=>{try{const t=tableFor(req);res.status(201).json((await upsert(t,req.body,req.companyId)).rows[0].data);}catch(e){next(e);}});
entityRouter.put('/:entity/:id',async(req,res,next)=>{try{const t=tableFor(req);res.json((await upsert(t,{...req.body,id:req.params.id},req.companyId)).rows[0].data);}catch(e){next(e);}});
entityRouter.delete('/:entity/:id',async(req,res,next)=>{try{const t=tableFor(req);if(t==='companies')return res.status(400).json({error:'Las empresas no se eliminan desde esta ruta.'});await pool.query(`DELETE FROM ${t} WHERE company_id=$1 AND id=$2`,[req.companyId,req.params.id]);res.status(204).end();}catch(e){next(e);}});
